### ISSUE TITLE
Hjelpetekst på alle sider

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-kunde-portal#10]
Alle sider burde ha en hjelpetekst nederst med en kort oppgavebeskrivelse som forklarer hvordan og hvorfor.

**Comment by fsjovatsen** [comment]
@asgeirn @oleanders @EilenA, har dere forslag til tekster?

**Comment by fsjovatsen** [comment]
Hva med noe slikt @asgeirn @oleanders @EilenA?

![image](https://user-images.githubusercontent.com/6375784/44058167-965af2ae-9f4d-11e8-9c8f-beb09b4e8360.png)

**Comment by asgeirn** [comment]
> Adaptere må registreres før de kan tas i bruk. Et adapter må få opprettet OAuth påloggingsinformasjon og bli gitt tilgang til de komponentene det skal levere data for.
> Påloggingsinformasjonen og informasjon om endepunkter må oppgis til den som skal installere og konfigurere adapteret.

**Comment by fsjovatsen** [comment]
Fixed
