### ISSUE TITLE
GDPR: Kommunikasjonsvalg

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-kunde-portal#11]
Gi personer mulighet for å velge hvilken informasjon, og i hvilke kanaler, de ønsker å motta.

**Comment by fsjovatsen** [comment]
Ettersom dette er informasjon brukeren trenger for å utføre arbeidsoppgavene sine så trenger vi ikke ett samtykke. Men vi legger på informasjon om hva informasjonen brukes til. Dette kommer i et nytt prosjekt for selvregistrering.
