### ISSUE TITLE
Selvregistrering

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-kunde-portal#12]
Legg til mulighet for selvregistrering.  Når ukjente personer logger på med IDporten kan de få muligheten for å registrere seg som personer i Kundeportalen. 

Her kan vi be om navn, epost og telefon, samt innhente samtykke for at informasjonen lagres.

**Comment by fsjovatsen** [comment]
Denne funksjonaliteten lages i et eget prosjekt.
