### ISSUE TITLE
Primær ressurs bør tilknyttes automatisk

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-kunde-portal#6]
Når nye klienter og adaptere opprettes bør de automatisk knyttes til primær ressurs.

Steget fra adapter til ressurs og tilbake til adapter er forvirrende og unødvendig for de fleste i første omgang.

**Comment by fsjovatsen** [comment]
Denne er fikset i `fint-portal-api` https://github.com/FINTprosjektet/fint-portal-api/releases/tag/v3.0.0-rc-19
